### ISSUE TITLE
errors (on google colab)

### ISSUE THREAD

**Issue by 0wwafa** [second-state/chatbot-ui#1]
```
git clone https://github.com/second-state/chatbot-ui.git
cd chatbot-ui
npm install
npm run dev
```

```
added 664 packages from 525 contributors and audited 699 packages in 44.136s

238 packages are looking for funding
  run `npm fund` for details

found 39 vulnerabilities (1 low, 24 moderate, 13 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> ai-chatbot-starter@0.1.0 dev /content/chatbot-ui
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000/
info  - Loaded env from /content/chatbot-ui/.env.local
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

/bin/sh: 1: yarn: not found
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
ReferenceError: AbortController is not defined
    at fetchCSSFromGoogleFonts (/content/chatbot-ui/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:34:28)
    at nextFontGoogleFontLoader (/content/chatbot-ui/node_modules/next/dist/compiled/@next/font/dist/google/loader.js:76:79)
    at /content/chatbot-ui/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:72:99
    at async Span.traceAsyncFn (/content/chatbot-ui/node_modules/next/dist/trace/trace.js:79:20)
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
event - compiled client and server successfully in 5.1s (272 modules)
wait  - compiling...
event - compiled successfully in 335 ms (232 modules)
error - API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
error - API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
error - API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
error - API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
error - API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
```

**Comment by 0wwafa** [comment]
The errors are probably due to the node version on google colab.
Just so you know.
